# Backend API service configuration for Google App Engine
runtime: nodejs22
service: api
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

env_variables:
  NODE_ENV: production
  DATABASE_URL: ${DATABASE_URL}
  JWT_SECRET: ${JWT_SECRET}
  CLOUD_STORAGE_BUCKET: ${CLOUD_STORAGE_BUCKET}
  CORS_ORIGIN: https://roadsignfactory.hk

handlers:
# API endpoints
- url: /api/.*
  script: auto
  secure: always

# Health check
- url: /health
  script: auto
  secure: always

# Block direct access to other paths
- url: /.*
  script: auto
  secure: always
  login: admin
